### ISSUE TITLE
Suggestion for H1 and maybe even for officer page

### ISSUE THREAD

**Issue by theKidOfArcrania** [pwnhs/pwnhs.github.io#2]
Since this website is limited to static infrastructure, may I suggest using a password-based encryption algorithm where the secret key of a cipher algorithm is generated directly from the student ID number, if you are planning on storing all the data of student standing for NHS in a JS array? This way, you could effectively lock out anyone from accessing student sensitive data without one vital information --- the student ID number.  I'm pretty sure there are plenty of different libraries that can accomplish just that.

You could also try checking the officer password after passing it through a message digest algorithm (such as SHA256) so you don't leak the actual password. Just a suggestion.

Also if you end up obfuscating the code for security purposes, don't just use the `function(p, a, c, k, e, d)`  packer. (You know what I mean)

**Comment by pwnhs** [comment]
perhaps a more lightweight method would be just to **obfuscate** and **compile** the JS arrays, given that the information is not very sensitive, but this is a very good point. we'll implement something like this as we begin to roll out the feature _(near December)_. if you come up with any other ideas or powerful libraries that accomplish what your issue suggests, please do tell.

**Comment by theKidOfArcrania** [comment]
You can use google's [CryptoJS](https://code.google.com/archive/p/crypto-js/) library to encrypt and decrypt data with military-grade encryption using the AES algorithm. Here is a [sample](https://gist.github.com/Xeoncross/5969760) (HTML and JS included) for how you would do that. You would probably use the student ID as the "secret passphrase". One way to verify whether if the student id is valid is to include a hash of some data points along with the other student data and encrypt the entire thing using the student ID. You may also consider attaching some salt and pepper to increase security.

And I object, this does not require too much code on the pwnhs side and should be lightweight, and obsfucation can always be reversed, and could easily be discovered. It is not useful in preventing exposure of data if you know where to look.

Also data such as student ID is pretty sensitive data; it's still used for various sites (including naviance and charms as passwords) and purposes. I also don't think every person would want their NHS standings shown to anyone unauthorized to handle the information.

**Comment by theKidOfArcrania** [comment]
Actually add to that, passphrase should constitute as your name and student ID (We have the user enter in name and student ID on different fields, and we concatenate the two fields together to make one passphrase)

**Comment by pwnhs** [comment]
We implemented an md5 encryption system to the IDs on the 'status-check' feature using [this library](https://github.com/emn178/js-md5).

> # But wait, md5 is a terrible hash function!

Yeah, that's true. We'll update it to SHA on November 15; we had to make the initial version in one hour.  

## Thank you so much for your insight.

Without this issue, we likely would have not updated anything until full implementation. For that, the PWNHS sincerely appreciates your support.  

While creating a key from both the student's ID and his/her name would be more secure, we must consider **the functional advantage** to this. Firstly, an attacker can do _very little_ with solely the student's ID - without access to a database of usernames, he cannot access Naviance or Charms. And while both are terrible platforms in their password handling, thankfully they implement a server-side lockout after three failed password attempts on a username. In reality, an attacker can do little more than buy some pizza sticks with a decrypted ID.  
Second, tying the student's name to their ID is a cumbersome procedure likely to fail - not because the implementation is difficult, but because the record of names is not totally correct. For whatever reason, a portion of names on file with the PWNHS are misspelled, likely out of human error, students' poor handwriting, or students' inattention when noting credentials. In addition, some students may have recorded a nickname or multiple names that are not their legal first name, and may become quite frustrated when they are not able to view what they need to on any PWNHS services.  

Again, **SHA + support for junior hours** will be available November 15 (coincidentally, also the date of Caltech's first admissions readings! Sorry, I'm quite 😬). At that time, we will provide you with the `source` and ask if you have any further suggestions before closing the issue. Thank you for your interest in PWNHS. Remember, fall hours are due Dec. 1!

**Comment by theKidOfArcrania** [comment]
Actually, how you are using it, I don't think SHA would be necessary; without a name attached to it, it is practically impossible to obtain any useful information. Although I do suggest you redact those membership documents from the [cdn](https://github.com/ayazhafiz/cdn) repository. I.e. if you follow this [link](https://github.com/ayazhafiz/cdn/raw/6907adce843a50fade49f1916e7bab501f0a61dd/nhs/officer/rosters/11.4.xlsm), anyone could find some discriminatory data ;) _Beware of what you put on the internet, because once it's there it will be difficult to remove it._

**Comment by ayazhafiz** [comment]
ah shoot you're right, I forgot to scrap it after I put it on the server lmao. thank you.

**Comment by ayazhafiz** [comment]
well, you got an inside scoop on the workings of NHS ;-). have fun with the VBA.

**Comment by theKidOfArcrania** [comment]
you know, those nice documents are still there (i.e. follow the link), 'cause Github preserves all of 'em commits. You gotta scrap the entire repository and start over if you really want to clean 'em up.

I'll have fun with the VBA in the spreadsheets --- (just a cool little fact, I actually started out learning programming with VBA)
